spring:
  application:
    name: ts-station-service
  data:
    mongodb:
      host: ts-station-mongo
      database: ts-station-mongo
      port: 27017

# HTTP Server
server:
  port: 12345  # HTTP (Tomcat) port

swagger:
  controllerPackage: fdse.microservice