# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  data:
    mongodb:
      host: ts-travel2-mongo
      database: ts-travel2-mongo
      port: 27017
swagger:
  controllerPackage: travel2.controller