spring:
  application:
    name: ts-consign-price-service
  data:
    mongodb:
      host: ts-consign-price-mongo
      database: ts-consign-price-mongo
      port: 27017


# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller