# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port

spring:
  application:
    name: ts-order-service
  data:
    mongodb:
      host: ts-order-mongo
      database: ts-order-mongo
      port: 27017

swagger:
  controllerPackage: order.controller