spring:
    application:
      name: ts-config-service
    data:
      mongodb:
        host: ts-config-mongo
        database: ts-config-mongo
        port: 27017

# HTTP Server
server:
  port: 15679  # HTTP (Tomcat) port

swagger:
  controllerPackage: config.controller
