# HTTP Server
server:
  port: 19001  # HTTP (Tomcat) port

spring:
  application:
    name: ts-payment-service
  data:
    mongodb:
      host: ts-payment-mongo
      database: ts-payment-mongo
      port: 27017

swagger:
  controllerPackage: com.trainticket.controller