server:
  port: 15678  # HTTP (Tomcat) port

spring:
  application:
    name: ts-verification-code-service
  cache:
    cache-names: tokens
    caffeine:
      maximumSize: 1000
      expiresAfterAccess: 600s

swagger:
  controllerPackage: verifycode.controller
