spring:
  application:
    name: ts-price-service
  data:
    mongodb:
      host: ts-price-mongo
      database: ts-price-mongo
      port: 27017


# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller