spring:
  application:
    name: ts-train-service
  data:
    mongodb:
      host: ts-train-mongo
      database: ts-train-mongo
      port: 27017

# HTTP Server
server:
  port: 14567  # HTTP (Tomcat) port

swagger:
  controllerPackage: train.controller