server:
  port: 18855

spring:
  application:
    name: ts-food-map-service
  data:
    mongodb:
      host: ts-food-map-mongo
      database: ts-food-map-mongo
      port: 27017

swagger:
  controllerPackage: food.controller
