# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-service
  data:
    mongodb:
      host: ts-travel-mongo
      database: ts-travel-mongo
      port: 27017
swagger:
  controllerPackage: travel.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831