server:
  port: 18673

spring:
  application:
    name: ts-inside-payment-service

  data:
    mongodb:
      host: ts-inside-payment-mongo
      database: ts-inside-payment-mongo
      port: 27017

swagger:
  controllerPackage: inside_payment.controller