spring:
  application:
    name: ts-security-service
  data:
    mongodb:
      host: ts-security-mongo
      database: ts-security-mongo
      port: 27017

# HTTP Server
server:
  port: 11188  # HTTP (Tomcat) port

swagger:
  controllerPackage: security.controller