spring:
  application:
    name: ts-consign-service
  data:
    mongodb:
      host: ts-consign-mongo
      database: ts-consign-mongo
      port: 27017


# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller